name: Semantic Automatic Version Releaser

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: draft-release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required to get full git history

      - name: Run Semantic Automatic Version Releaser
        uses: ./
        with:
          github-token: ${{ github.token }}
